### ISSUE TITLE
events lost when server sockets and client sockets share IDs

### ISSUE THREAD

**Issue by trevj** [freedomjs/freedom-for-chrome#55]
It seems client and server sockets share the same namespace. This is a bit surprising to me and may be new behaviour in Chrome 41 but I don't see anything in the documentation to indicate otherwise.

This is *particularly* a problem when Chrome has just started: consider a simple Freedom app which creates one client and one server socket and tries to send data between them. Both sockets will have an ID of 1 which, internally, core.tcpsocket can't handle (examine its `Socket_chrome.active` map).

Discovered this while adding integration tests:
https://github.com/uProxy/uproxy/issues/628

**Comment by trevj** [comment]
BTW, this doesn't happen in Firefox.

**Comment by willscott** [comment]
Addressed in https://github.com/freedomjs/freedom-for-chrome/pull/56
