### ISSUE TITLE
rename integration task to avoid naming collision with freedom-for-firefox

### ISSUE THREAD

**Issue by trevj** [freedomjs/freedom-for-chrome#57]
We would like to add integration tests for both Chrome Firefox add-ons but the relevant task name in both freedom-for-chrome and freedom-for-firefox is integration, making this impossible. We should rename the task, e.g. `integration_chrome`.

Related:
https://github.com/freedomjs/freedom-for-firefox/issues/46

**Comment by ryscheng** [comment]
https://github.com/willscott/grunt-jasmine-chromeapp
