### ISSUE TITLE
report consistent errors from core.tcpsocket

### ISSUE THREAD

**Issue by ryscheng** [freedomjs/freedom-for-chrome#64]
As part of this pull request
https://github.com/freedomjs/freedom-for-chrome/pull/63

I've reverted some of your changes from here:
https://github.com/freedomjs/freedom-for-chrome/commit/31f8677dffd5ebeb87a6693cd8af6112b5e89a1f#commitcomment-9574685

Right now, firefox and node don't report NAME_NOT_RESOLVED. We need to make sure that all errors are consistent and reflected in the core.tcpsocket integration tests run against all platforms.

Let's discuss what you want here

**Comment by bemasc** [comment]
I don't think our error codes should be restricted to the least common denominator of all supported platforms.  Rather, we should have some minimal requirements for clarity of error code returns, and implementations should feel free to be more detailed when possible.

**Comment by willscott** [comment]
This seems fine. I think it was more just that we hadn't realized that the
previous change caused the test to fail, and once we caught that we wanted
to make sure we got the test updated as part of the change.

**Comment by bemasc** [comment]
OK, I'll send a new pull request that doesn't break the tests.

**Comment by bemasc** [comment]
Test updated by https://github.com/freedomjs/freedom/pull/222.  I suppose I need to wait for a freedom version bump before making the corresponding change in freedom-for-chrome.

**Comment by ryscheng** [comment]
Ah cool. Thanks for the pull request in freedom. I've fixed freedom-for-chrome to be what you originally had
