### ISSUE TITLE
Add `main` param to the package to support `require.resolve` usage

### ISSUE THREAD

**Issue by iislucas** [freedomjs/freedom-for-chrome#71]
It's quite convenient in freedom that the package.json file specified a main: https://github.com/freedomjs/freedom/blob/master/package.json#L18

Lets do the same for freedom-for-chrome as it makes it easier for other packages to use it and not worry about paths to the created freedom-for-chrome.js file.

**Comment by willscott** [comment]
Also addressed for firefox https://github.com/freedomjs/freedom-for-firefox/commit/b3ee79edbe46ad3496be5db594818e46d6e9a4e6

**Comment by iislucas** [comment]
Thanks for the awesome fast turnaround. I'll away the next release and then
I can cleanup uproxy-networking require cleanup a bit more :)

On Thu, Feb 26, 2015 at 11:50 AM, Will <notifications@github.com> wrote:

> Also addressed for firefox freedomjs/freedom-for-firefox@b3ee79e
> <https://github.com/freedomjs/freedom-for-firefox/commit/b3ee79edbe46ad3496be5db594818e46d6e9a4e6>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freedomjs/freedom-for-chrome/issues/71#issuecomment-76215199>
> .
>



-- 
Lucas Dixon | Google Ideas
