### ISSUE TITLE
Add support for HOST_UNREACHABLE

### ISSUE THREAD

**Issue by iislucas** [freedomjs/freedom-for-chrome#73]
In 
https://github.com/uProxy/uproxy-networking/blob/dev/src/integration/socks-echo/socks-echo.integration.spec_base.ts#L305

We have disabled an integration test pending on freedom-for-chrome supporting a HOST_UNREACHABLE error. But then I realised there wasn't a tracking issue for it. So I made this.

**Comment by soycode** [comment]
After some investigation, I think what we need is to just map an additional error code in the provider (https://github.com/freedomjs/freedom-for-chrome/commit/354f39e3f04c815f17933728330fb17ab9ccbe92) and also add it to the interface (https://github.com/freedomjs/freedom/commit/6f81a4d100baaecf25be2fcee37963459f6cb07f). The Chrome provider already has logic to then surface the appropriate error when it occurs.

LMK thoughts, I'll include the freedom repo commit in my ongoing TCP tests pull request, and make a freedom-for-chrome pull request as well if this seems to be the right approach.

**Comment by iislucas** [comment]
SGTM!
